//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "agent")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub language: String,
    pub directory: String,
    #[sea_orm(column_type = "Double")]
    pub rating: f64,
    #[sea_orm(column_type = "Double")]
    pub total_score: f64,
    pub num_games: i32,
    pub removed: bool,
    pub error_file: Option<String>,
    pub source_file: Option<String>,
    pub in_game: bool,
    pub owner_id: Option<i32>,
    pub partial: bool,
    pub colour: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::OwnerId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
